### ISSUE TITLE
DBをBigQueryを利用するように修正

### ISSUE THREAD

**Issue by sakamomo554101** [sakamomo554101/YouyakuAI#21]
# 概要

DBをBQに保存するように対応
現状は、（別コンテナ化しているが）MySQLへ保存するように対応している。

上記のDBヘルパー的なインスタンスをBQ用にも作成し、データを保存できるようにする。

**Comment by sakamomo554101** [comment]
これやりたい。

**Comment by sakamomo554101** [comment]
https://github.com/googleapis/python-bigquery
上記に色々とサンプルがある

**Comment by sakamomo554101** [comment]
https://googleapis.dev/python/bigquery/latest/index.html
上記がBQのAPI情報とかある

**Comment by sakamomo554101** [comment]
BQだと、project_id -> dataset -> tableという階層になっている。
なので、database = datasetとすれば、現状のmysqlのAPIと構造が一致するな。

**Comment by sakamomo554101** [comment]
BQのテーブル作成をどうやるか。
現状はテーブルのスキーマ情報をコードにベタ書き（SQLAlchemyのモデルクラスにベタ書き）している。
上記スキーマ情報をどうBQのAPIに渡すか。

* jsonスキーマでテーブル情報を定義し直して、SQLAlchemyにjsonのスキーマ情報を渡す
* SQLAlchemyのモデルクラスをうまくBQのスキーマ情報に変換する

**Comment by sakamomo554101** [comment]
https://www.python.ambitious-engineer.com/archives/1481
上記を参考にしつつ、SQLAlchemyのスキーマ情報をBQ側に反映させる

**Comment by sakamomo554101** [comment]
BigQueryだと、primary keyやindexの概念がなさそう

**Comment by sakamomo554101** [comment]
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableFieldSchema.FIELDS.mode
BQのmode（値の扱いをどうするか）は上記。

required, nullableは良いとして、REPEATEDってなんぞ？

**Comment by sakamomo554101** [comment]
https://programwiz.org/2021/05/29/bigquery-difference-datetime-and-timestamp/
BQだと、datetimeとtimestampの型がある。
違いは、タイムゾーンを意識するかどうか。timestampは意識している。

どっち使えば良いかなー。

**Comment by sakamomo554101** [comment]
https://docs.sqlalchemy.org/en/14/tutorial/metadata.html#setting-up-the-registry
registry.metadataで、テーブルのスキーマを格納しているmetadataが取れる

**Comment by sakamomo554101** [comment]
あ、BQだと、autoincrementなカラムはどう扱えばいいんだろ？

**Comment by sakamomo554101** [comment]
https://qiita.com/kurukuruz/items/4d3569edf40582259d1b

**Comment by sakamomo554101** [comment]
https://cloud-textbook.com/3635/#auto_increment

そうか、、根本的に直す必要がありそう・・

**Comment by sakamomo554101** [comment]
UUIDをgenerateさせるのはありか

**Comment by sakamomo554101** [comment]
あー、そうか。。正式なパスでテーブル名を指定する必要があるんだ・・。

この場合だと、project_name.dataset_name.table_nameだな

**Comment by sakamomo554101** [comment]
とりあえず、uuidをstringに変換して、BQに入れ直す

**Comment by sakamomo554101** [comment]
なるほど、、insertのタイミングでuuid付与しているから、BodyInfoのインスタンス作ったタイミングでは、まだidがない状態なんだ・・。

MySQLの場合、かってにIDが割り振られる前提だからOK

**Comment by sakamomo554101** [comment]
# 方針

* DBの各テーブルのidをuuid対応させる（MySQL、BQでの動作検証を実施する）

**Comment by sakamomo554101** [comment]
あれ、、SQLAlchemyのcolumnに対して、初期化が聞いてないような・・。
dataclassだから？

**Comment by sakamomo554101** [comment]
https://docs.python.org/ja/3/library/dataclasses.html#post-init-processing
__post_init__でuuidの初期化すれば良いかも。試す。

**Comment by sakamomo554101** [comment]
summarize_job_infoとsummarize_job_logのidに差分がある・・

**Comment by sakamomo554101** [comment]
* job_idはqueue側でuuidを作っているため、DB側で初期化不要（他のidはdb側で初期化する）

**Comment by sakamomo554101** [comment]
MySQL側、BQ側、両方要約処理のレスポンス変えることを確認！

IFの型を整理したら、コミット整理して、PR作る！

**Comment by sakamomo554101** [comment]
テストも見た方がいいな。
特にMySQL側はこけそう

**Comment by sakamomo554101** [comment]
うーむ、テストコード動かん・・。

とりあえずAPI_Gatewayから見ていく。

```
======================================================================
ERROR: test_get_summarize_result_complete (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "api_gateway/test/test_api.py", line 84, in test_get_summarize_result_complete
    response = client.get(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/starlette/testclient.py", line 468, in request
    return super().request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/starlette/testclient.py", line 266, in send
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/testclient.py", line 263, in send
    portal.call(self.app, scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/anyio/from_thread.py", line 230, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/anyio/from_thread.py", line 177, in _call_func
    retval = await retval
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "api_gateway/test/../api.py", line 96, in get_summarize_result
    return await self.__get_summarize_result(job_id=job_id)
  File "api_gateway/test/../api.py", line 126, in __get_summarize_result
    job_log = self.__db_instance.fetch_summarize_job_log_by_id(job_id=job_id)
  File "api_gateway/test/test_api.py", line 196, in fetch_summarize_job_log_by_id
    return [job_log for job_log in self.__job_logs if job_log.job_id == job_id][0]
IndexError: list index out of range

======================================================================
FAIL: test_request_summarize (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "api_gateway/test/test_api.py", line 59, in test_request_summarize
    self.assertEqual(len(queue), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_set_correct_summarize_result_complete (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "api_gateway/test/test_api.py", line 119, in test_set_correct_summarize_result_complete
    self.assertEqual(response.status_code, 200)
AssertionError: 422 != 200

----------------------------------------------------------------------
Ran 3 tests in 0.069s

FAILED (failures=2, errors=1)
```

**Comment by sakamomo554101** [comment]
結構まえのキューの実装修正した際のテストコードの修正ミスっぽいな・・。
やっぱりちゃんとテストを毎回全部実行したい・・

**Comment by sakamomo554101** [comment]
test_apiは書き直す

```
======================================================================
FAIL: test_set_correct_summarize_result_complete (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_api.py", line 125, in test_set_correct_summarize_result_complete
    self.assertEqual(response.status_code, 200)
AssertionError: 422 != 200
```

**Comment by sakamomo554101** [comment]
CorrectInputDataにstatus_codeは不要そうなので、削除する。
api.jsonも修正する（これどうやって作ったっけ・・）

**Comment by sakamomo554101** [comment]
test_db_wrapper.pyもこけているので修正する。
※これはBQ対応が関連してそう

**Comment by sakamomo554101** [comment]
test_bq_db_wrapperもこけてるな・・。

**Comment by sakamomo554101** [comment]
各idをfetch時に入れ直す必要がある

**Comment by sakamomo554101** [comment]
一通りテストパスしたので、コミット整理して、マージする。
テスト追加するissueは作っておこ・・

**Comment by sakamomo554101** [comment]
対応済み。クローズ。
