### ISSUE TITLE
VertexAIのパイプラインに学習パイプラインを構築する

### ISSUE THREAD

**Issue by sakamomo554101** [sakamomo554101/YouyakuAI#24]
## 対応内容

#16 から派生。

* VertexAIのパイプラインを用いて、学習パイプラインを構築する
* ドキュメント整理（学習時の手順）

**Comment by sakamomo554101** [comment]
進める

**Comment by sakamomo554101** [comment]
確かVertexAI利用時は、アカウントに対して利用権限が必要＋Enable対応があったような。確認する。

**Comment by sakamomo554101** [comment]
構成を変えるか。
VertexAI Predictionを使うことも加味すると、以下の流れとなる。

* VertexAIのEnable対応
* GCRにプッシュするスクリプトの作成
* VertexAI Pipelineにプッシュして、学習パイプラインを動かすスクリプトの作成
* T5モデルを稼働させるためのコンテナを作成＋Restで呼び出す実装に修正（Summarizerを分割するイメージ）
  * ローカルコンテナでの動作パターンと、VertexAI Predictionでの動作パターンの二つが存在するイメージ
 * ドキュメントの修正

**Comment by sakamomo554101** [comment]
VertexAIのEnable対応は、GCPコンソールから実施

**Comment by sakamomo554101** [comment]
GCPでの処理のために、gcloudコマンドは必須。
ドキュメントにセットアップ手順を書いておく。

下記
https://cloud.google.com/sdk/docs/install?hl=JA

**Comment by sakamomo554101** [comment]
https://github.com/reproio/lab_sample_pipelines/blob/main/kfp/deploy_all_component.sh

あばば、Dockerfileにコードを含める対応や、エントリポイントの設定対応が必要そう？
※学習パイプラインのみなら大丈夫かも？

**Comment by sakamomo554101** [comment]
あ、model_pipeline配下でもう作ってたのか

**Comment by sakamomo554101** [comment]
pipelineの構築の多様性を考えるなら、ちょっとyamlの構成を考え直すか。
deploy.ymlのこと。

**Comment by sakamomo554101** [comment]
project_idは削除しておくか（yamlから実の値を除外）

**Comment by sakamomo554101** [comment]
https://cloud.google.com/container-registry/docs/advanced-authentication
GCRのpush時に権限が必要そう

**Comment by sakamomo554101** [comment]
https://cloud.google.com/container-registry/docs/access-control
以下の権限を付与すれば良さそう。

* ストレージ管理者（push）
* ストレージオブジェクト管理者（pull）

**Comment by sakamomo554101** [comment]
https://qiita.com/sabure500/items/ff8512988008de4734ae

**Comment by sakamomo554101** [comment]
https://qiita.com/suzuyui/items/24e9ba8590deea17c456
artifact registryを試してみるかなー

**Comment by sakamomo554101** [comment]
そうか、サービスアカウントをスクリプトで全部作るようにしちゃうのはありだな。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/container-registry/docs/advanced-authentication#gcloud
サービスアカウントでログインして、dockerログインする必要があるのか。

**Comment by sakamomo554101** [comment]
https://genzouw.com/entry/2021/06/19/082626/2661/
yamlはエイリアス機能で、定数の使い回しが可能

**Comment by sakamomo554101** [comment]
docker push時に以下のエラー。
権限付与しないと。

```
denied: Token exchange failed for project 'youyaku-ai'. Caller does not have permission 'storage.buckets.create'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
```

**Comment by sakamomo554101** [comment]
下記が必要？

```
gcloud auth configure-docker
```

**Comment by sakamomo554101** [comment]
変わらず。

**Comment by sakamomo554101** [comment]
GCRのstorage bucketって、どうやって紐づいているん？

**Comment by sakamomo554101** [comment]
なるほど。

* GCRのコンテナイメージはCloud Storageで管理される（格納される）
* 最初、適当にイメージをプッシュすると、バケットが作成される（ここで、エラーになっている）
  * パーミッションとしては、ストレージ管理者権限レベルでpush処理が必要（これをどうやって設定すれば良い？）

**Comment by sakamomo554101** [comment]
* memo
  * サービスアカウントの権限追加は、IAMのページから編集で設定可能

**Comment by sakamomo554101** [comment]
deploy.ymlはenvのパラメーター みるようにするとか対応したいな。
GCPのプロジェクトIDを重複して書くとかはやめたい。

**Comment by sakamomo554101** [comment]
VertexAI パイプラインを使う場合は、どのような権限が必要？

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/pipelines/configure-project
上記読む

**Comment by sakamomo554101** [comment]
多分、下記のロール相当の権限があれば、良さそう。

* roles/aiplatform.user

**Comment by sakamomo554101** [comment]
とりあえず、AI Platform Developerを付与してみた

**Comment by sakamomo554101** [comment]
https://cam-inc.co.jp/p/techblog/582520922968163131

下記のようにパイプライン実行が可能。

```python
from kfp.v2.google.client import AIPlatformClient
 
GCP_PROJECT_ID="gcp_project_id"
REGION="asia-east1"
 
api_client = AIPlatformClient(project_id=GCP_PROJECT_ID, region=REGION)
 
COMPILED_PIPELINE_PATH= './lgbm-train-pipeline.json'
ENABLE_CACHING=False
PIPELINE_PARAMETERS={"is_deployed":"True",
                    "target_date":"20210901",
                   }
 
pipeline_run_name = api_client.create_run_from_job_spec(
   job_spec_path=COMPILED_PIPELINE_PATH,
   parameter_values=PIPELINE_PARAMETERS,
   enable_caching=ENABLE_CACHING,
)
```

**Comment by sakamomo554101** [comment]
実装がかなり汚いな・・。ちょっと整理したいところ。
まずは動かすようにするか。

**Comment by sakamomo554101** [comment]
AIPlatformClientの取得に失敗する。
下記エラー。GOOGLE_APPLICATION_CREDENTIALSは設定しているんだが、、

```
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by sakamomo554101** [comment]
GOOGLE_APPLICATION_CREDENTIALSをターミナルで入れたら、違うエラーになったが、、。
うーん、、makefileでGOOGLE_APPLICATION_CREDENTIALSを設定しても、環境変数情報が使えない？

**Comment by sakamomo554101** [comment]
今度パーミッションエラー。

```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://us-central1-aiplatform.googleapis.com/v1beta1/projects/youyaku-ai/locations/us-central1/pipelineJobs?pipelineJobId=youyaku-ai-pipeline-20211103111020&alt=json returned "Permission 'aiplatform.pipelineJobs.create' denied on resource '//aiplatform.googleapis.com/projects/youyaku-ai/locations/us-central1' (or it may not exist).". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'IAM_PERMISSION_DENIED', 'domain': 'aiplatform.googleapis.com', 'metadata': {'permission': 'aiplatform.pipelineJobs.create', 'resource': 'projects/youyaku-ai/locations/us-central1'}}]">
make: *** [run-pipeline] Error 1
```

**Comment by sakamomo554101** [comment]
試しにVertex AIユーザーのロールをサービスアカウントに付与。

**Comment by sakamomo554101** [comment]
サービスアカウントにVertex AI管理者ロールを付与したら、以下のエラーになった。
サービスアカウントの実行権限がない？

```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://us-central1-aiplatform.googleapis.com/v1beta1/projects/youyaku-ai/locations/us-central1/pipelineJobs?pipelineJobId=youyaku-ai-pipeline-20211103111851&alt=json returned "You do not have permission to act as service_account: youyaku-ai-account@youyaku-ai.iam.gserviceaccount.com. (or it may not exist).". Details: "You do not have permission to act as service_account: youyaku-ai-account@youyaku-ai.iam.gserviceaccount.com. (or it may not exist).">
```

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/pipelines/configure-project#service-account
上記を正しく対応すれば良いんだろうけど、サービスアカウントとユーザーを紐づける意味がよくわかってないな・・

**Comment by sakamomo554101** [comment]
cloud resource managerのAPIを有効化する必要がありそう

**Comment by sakamomo554101** [comment]
Cloud Resource Manager APIをGCPコンソールから有効化した

**Comment by sakamomo554101** [comment]
自分のオーナーアカウントでログインし直して、再度IAM設定をしたら、うまくいった（IAM設定が）

```
$ gcloud config set account <mail address>
$ gcloud auth login -> 認証画面へ遷移して、認証OKさせる
$ gcloud projects add-iam-policy-binding PROJECT_ID \
    --member="serviceAccount:SERVICE_ACCOUNT_ID@PROJECT_ID.iam.gserviceaccount.com" \
    --role="roles/aiplatform.user"
```

**Comment by sakamomo554101** [comment]
https://qiita.com/kobori_akira/items/9620fa137419f7fb700b

**Comment by sakamomo554101** [comment]
オーナー権限のあるメールアドレスとサービスアカウントを紐づけたが、"You do not have permission to act as service_account.."のエラーは変わらず・・

**Comment by sakamomo554101** [comment]
サービスアカウントを作り直してみるかなぁ・・

**Comment by sakamomo554101** [comment]
https://zenn.dev/catnose99/scraps/87846cb2fdf8ad
サービスアカウントユーザーを設定すれば良い？

**Comment by sakamomo554101** [comment]
サービスアカウントユーザーなんぞないんだが・・

**Comment by sakamomo554101** [comment]
下記コマンドでサービスアカウントユーザーの権限つきそうだが、、なんでだ・・。

```
gcloud iam service-accounts add-iam-policy-binding \
    SERVICE_ACCOUNT_ID@PROJECT_ID.iam.gserviceaccount.com \
    --member="user:USER_EMAIL" \
    --role="roles/iam.serviceAccountUser"
```

**Comment by sakamomo554101** [comment]
サービスアカウント作り直してもダメなんだが、、、なにこれ？

**Comment by sakamomo554101** [comment]
https://stackoverflow.com/questions/64236468/cloud-build-fails-to-deploy-to-google-app-engine-you-do-not-have-permission-to

**Comment by sakamomo554101** [comment]
まじか、、下記のようにしたら、エラー変わった・・。たぶん権限が正常に設定されたくさい。
※ようは実行するサービスアカウントに対して、同一サービスアカウントを実行ロールとして設定している。こんなこと必要なんかなぁ・・

```
gcloud projects add-iam-policy-binding ${GOOGLE_PROJECT_ID} --member="serviceAccount:${GOOGLE_SERVICE_ACCOUNT}" --role="roles/iam.serviceAccountUser"
```

**Comment by sakamomo554101** [comment]
パラメーターを設定したら、以下のエラー。
多分、GCSのバケット名が違いそうか、作る必要がある。

```
Failed to create pipeline job. Error: The GCS bucket "youyaku_ai_pipeline_vertex_ai" does not exist. Please check the path and try again..
```

**Comment by sakamomo554101** [comment]
makefileやセットアップまわりは整理しないとだけど、とりあえずパイプラインが動き出したぜ・・

**Comment by sakamomo554101** [comment]
trainerdでこけた。
なんで下記エラーが・・？

```
AssertionError: data frame columns count is not 3. columns is Index(['body', 'genre_id'], dtype='object')
```

**Comment by sakamomo554101** [comment]
model_pipelineのテストがさくっと動かせないのはちと問題だな・・

**Comment by sakamomo554101** [comment]
Trainer内部で、csvからDataFrameを渡した際の挙動がおかしい？

**Comment by sakamomo554101** [comment]
下記が悪さしてそうだなぁ・・。テストコードとの差分を見るか。

```
★dataset.py

train_dataset = pd.read_csv(args.train_data_path, index_col=0)
val_dataset = pd.read_csv(args.val_data_path, index_col=0)
test_dataset = pd.read_csv(args.test_data_path, index_col=0)
```

**Comment by sakamomo554101** [comment]
trainerでテスト動かしたら、普通にテストこけてるんだが笑

```
 > [test_runner 3/3] RUN python3 -m unittest:                                                                                                                                                                                 
#12 8.100 /component/tests/test_main.py:19: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.                 
#12 8.100   return yaml.load(f)                                                                                                                                                                                               
#12 8.100 /component/src/trainer.py:73: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.                     
#12 8.100   parameters = yaml.load(args.parameters)                                                                                                                                                                           
#12 8.100 EE
#12 8.102 ======================================================================
#12 8.102 ERROR: test_main (tests.test_main.TestTrainer)
#12 8.102 ----------------------------------------------------------------------
#12 8.102 Traceback (most recent call last):
#12 8.102   File "/component/tests/test_main.py", line 37, in test_main
#12 8.102     model = main(args=self.args)
#12 8.102   File "/component/src/trainer.py", line 73, in main
#12 8.102     parameters = yaml.load(args.parameters)
#12 8.102   File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 112, in load
#12 8.102     loader = Loader(stream)
#12 8.102   File "/usr/local/lib/python3.8/site-packages/yaml/loader.py", line 24, in __init__
#12 8.102     Reader.__init__(self, stream)
#12 8.102   File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
#12 8.102     self.determine_encoding()
#12 8.102   File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
#12 8.102     self.update_raw()
#12 8.102   File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
#12 8.102     data = self.stream.read(size)
#12 8.102 AttributeError: 'dict' object has no attribute 'read'
#12 8.102 
#12 8.102 ======================================================================
#12 8.102 ERROR: test_main (tests.test_main.TestTrainer)
#12 8.102 ----------------------------------------------------------------------
#12 8.102 Traceback (most recent call last):
#12 8.102   File "/component/tests/test_main.py", line 34, in tearDown
#12 8.102     shutil.rmtree(self.out_dest.trained_model_dir)
#12 8.102   File "/usr/local/lib/python3.8/shutil.py", line 709, in rmtree
#12 8.102     onerror(os.lstat, path, sys.exc_info())
#12 8.102   File "/usr/local/lib/python3.8/shutil.py", line 707, in rmtree
#12 8.102     orig_st = os.lstat(path)
#12 8.102 FileNotFoundError: [Errno 2] No such file or directory: '/component/tests/output'
#12 8.102 
#12 8.102 ----------------------------------------------------------------------
#12 8.102 Ran 1 test in 0.008s
#12 8.102 
#12 8.102 FAILED (errors=2)
------
```

**Comment by sakamomo554101** [comment]
あ、テストでも同じエラーになっとる

**Comment by sakamomo554101** [comment]
修正して、再度パイプラインで処理を実行中

**Comment by sakamomo554101** [comment]
下記のエラーが謎すぎる・・

```
fuse: writeMessage: no such file or directory [16 0 0 0 218 255 255 255 188 1 0 0 0 0 0 0]
```

**Comment by sakamomo554101** [comment]
下記みると、メモリ不足になってる？

```
The replica workerpool0-0 ran out-of-memory and exited with a non-zero status of 137(SIGKILL). To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=749925056555&resource=ml_job%2Fjob_id%2F1796995624948727808&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.label
```

**Comment by sakamomo554101** [comment]
マシンタイプはe2-standard-4で実行されてそう

**Comment by sakamomo554101** [comment]
https://gcpinstances.doit-intl.com/
上記でGCPのマシンタイプのリストが見れる。
16Gibだとちょっと足らんかも。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/pipelines/build-pipeline
お、メモリリミットとか設定できそう？

**Comment by sakamomo554101** [comment]
https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.Sidecar.set_memory_request
多分、set_memory_requestが良さそう。（リミットだと上限だしなぁ）

**Comment by sakamomo554101** [comment]
おぉ、set_memory_limitで32Gにしたら、インスタンスタイプ がe2-highmem-4に変わった！

**Comment by sakamomo554101** [comment]
GPU使う場合は、add_node_selector_constraintを設定すれば良さそう。
key-valueっぽいが、どう設定すれば良いか？

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/training/configure-compute#specifying_gpus
上記がGPUの種類。

以下のように設定するみたい。
```
add_node_selector_constraint('cloud.google.com/gke-accelerator', 'nvidia-tesla-k80')
```

**Comment by sakamomo554101** [comment]
へー、以下のように高いメモリインスタンスを使いたい！という指定もできるっぽい。

https://techblog.zozo.com/entry/aip-pipelines-impl
```
add_node_selector_constraint('cloud.google.com/gke-nodepool', 'high-memory-pool')
```

**Comment by sakamomo554101** [comment]
NVIDIA_TESLA_K80を使ってみるか

**Comment by sakamomo554101** [comment]
n1-highmem-8になってる（NVIDIA_TESLA_K80を指定したら）

**Comment by sakamomo554101** [comment]
あれ、GPU使われてなさそう。

```
GPU available: False, used: False
```

**Comment by sakamomo554101** [comment]
set_gpu_limitもいれてみる

**Comment by sakamomo554101** [comment]
うーん、GPU available: Falseになるなぁ。（set_gpu_limit(1)を入れても）

**Comment by sakamomo554101** [comment]
学習の進捗がわからん・・。
ローカルで実行すると、プログレスがみれるが、VertexAIのログ上だと、わからん・・。
TFBoardとかに残したい。

**Comment by sakamomo554101** [comment]
# 課題点

* GPUが使えない
* 学習の進捗が見えない

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/training/code-requirements#tensorboard
学習の可視化は上記見れば良いかも。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/blog/ja/topics/developers-practitioners/pytorch-google-cloud-how-train-pytorch-models-ai-platform
うーん、pytorchのDocker Imageが問題？

**Comment by sakamomo554101** [comment]
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch
nvidiaのpytorchイメージを取ればいいかなぁ

**Comment by sakamomo554101** [comment]
https://www.kubeflow.org/docs/distributions/gke/pipelines/enable-gpu-and-tpu/#configure-containerop-to-consume-gpus
上記でGPU使えそうなんだけどなぁ

**Comment by sakamomo554101** [comment]
下記のエラーで、Nvidia Driverが入ってなさそう。

```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by sakamomo554101** [comment]
https://cloud.google.com/blog/ja/topics/developers-practitioners/scalable-ml-workflows-using-pytorch-kubeflow-pipelines-and-vertex-pipelines

**Comment by sakamomo554101** [comment]
https://github.com/amygdala/code-snippets/blob/master/ml/vertex_pipelines/pytorch/cifar/pytorch_cifar10_vertex_pipelines.ipynb
https://github.com/amygdala/code-snippets/blob/master/ml/vertex_pipelines/pytorch/cifar/Dockerfile-gpu#L15

上記見ると、Dockerfileが違うなぁ

**Comment by sakamomo554101** [comment]
モデル保存でこけてた

```
2021-11-04T05:45:27.256672631ZTraceback (most recent call last):
エラー
2021-11-04T05:45:27.256699791Z File "/component/src/trainer.py", line 168, in <module>
エラー
2021-11-04T05:45:27.256706251Z model.save(
エラー
2021-11-04T05:45:27.256710241ZTypeError: save() got an unexpected keyword argument 'model'
```

**Comment by sakamomo554101** [comment]
GPUが動くはずのコンテナにしたら、下記エラーでジョブがお亡くなりに・・。なぜに・・
```
"The replica workerpool0-0 exited with a non-zero status of 139(SIGSEGV). Termination reason: Error
```

sigsegか・・

**Comment by sakamomo554101** [comment]
https://cloud.google.com/ai-platform/training/docs/understanding-training-service#common-errors

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/training/pre-built-containers#pytorch
上記を使ってみるか。

これだと、GCPベースになってしまう気がするが、とりあえずということで・・

**Comment by sakamomo554101** [comment]
以下のエラーに変わったが、、以前詳細わからん・・。
ただ、GPUを二つにしてることで、重複して学習処理が走ってる。一旦GPUを1つに制限して、試す。

```
The replica workerpool0-0 exited with a non-zero status of 1. Termination reason: Error
```

**Comment by sakamomo554101** [comment]
うーむ、VertexAIのログがなんかリアルタイムじゃない印象・・。
まとめてログが一気に表示されるので、なんとも処理状況が追いづらい・・

**Comment by sakamomo554101** [comment]
ログ見ると、とりあえずGPUは使うようになってるので、Docker Imageは問題ないかもしれない。

**Comment by sakamomo554101** [comment]
#43 でPR立てた

**Comment by sakamomo554101** [comment]
set_gpu_limit(1)にしても、下記エラー。

```
The replica workerpool0-0 exited with a non-zero status of 1
```

**Comment by sakamomo554101** [comment]
試しにメモリを64Gにあげて、試す・・。
しかし、32GBも使うはずないんだが、、

**Comment by sakamomo554101** [comment]
同じエラーか・・。どうすりゃいいんだ・・

**Comment by sakamomo554101** [comment]
VertexAI Workbench（Notebook）を使って、1行ずつデバッグするのがいいんかねぇ・・

**Comment by sakamomo554101** [comment]
まさかストレージが足りないとかあるのかな・・

**Comment by sakamomo554101** [comment]
https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.Sidecar.set_ephemeral_storage_limit
ストレージのサイズの上限を設けるのは上記でできるかも？

**Comment by sakamomo554101** [comment]
pytorch/pytorchのImageにしたら、以下のエラー。

```

エラー
2021-11-06T14:32:33.709273433Z File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 803, in select_accelerator
エラー
2021-11-06T14:32:33.709279652Z accelerator = acc_cls(training_type_plugin=self.training_type_plugin, precision_plugin=self.precision_plugin)
エラー
2021-11-06T14:32:33.709285574Z File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 399, in precision_plugin
エラー
2021-11-06T14:32:33.709291123Z self._precision_plugin = self.select_precision_plugin()
エラー
2021-11-06T14:32:33.709297268Z File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 614, in select_precision_plugin
エラー
2021-11-06T14:32:33.709317182Z f"You have asked for `amp_level={self.amp_level!r}` but it's only supported with `amp_backend='apex'`."
エラー
2021-11-06T14:32:33.709328874Zpytorch_lightning.utilities.exceptions.MisconfigurationException: You have asked for `amp_level='O1'` but it's only supported with `amp_backend='apex'`.
エラー
2021-11-06T14:32:48.105185817ZThe replica workerpool0-0 exited with a non-zero status of 1. Termination reason: Error
```

**Comment by sakamomo554101** [comment]
下記エラーが出てる。oomっぽい。

```
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 7.43 GiB total capacity; 6.46 GiB already allocated; 54.81 MiB free; 6.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by sakamomo554101** [comment]
http://fruitsoflife.sblo.jp/article/189004809.html
https://pytorch.org/docs/stable/notes/cuda.html

**Comment by sakamomo554101** [comment]
試しにPYTORCH_NO_CUDA_MEMORY_CACHING=1を入れてみるか。
GPU上のメモリ（RAM）のキャッシュによりOOMになってそうなので。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/compute/docs/gpus#other_available_nvidia_gpu_models
上記見ると、P4は8GiBか。やや足らんかも。

**Comment by sakamomo554101** [comment]
お、P100にしたら、処理通ったな！
モデルの保存処理でこけてるけど・・。

だいぶ早いな〜

**Comment by sakamomo554101** [comment]
エラーは下記。

```
2021-11-07T02:31:56.518211672ZTraceback (most recent call last):
エラー
2021-11-07T02:31:56.518237895Z File "/component/src/trainer.py", line 196, in <module>
エラー
2021-11-07T02:31:56.518246793Z model=model, model_dir=artifacts.output_destinations.trained_model_dir
エラー
2021-11-07T02:31:56.518255057ZTypeError: save() got an unexpected keyword argument 'model'
```

**Comment by sakamomo554101** [comment]
なんかsaveのパラメーター設定がおかしいから修正して、再度デプロイ＆Run。
これでうまくいけばいいけども。

GPUだと20分くらいで学習終わるなー。

**Comment by sakamomo554101** [comment]
やっと学習パイプライン動いた！！！モデルファイルできているかを確認するか。

**Comment by sakamomo554101** [comment]
モデルファイルができていることを確認。

**Comment by sakamomo554101** [comment]
# 残件

* num_train_epochs = 8でモデル構築されるかを確認
* パイプラインの実行手順（準備含む）をREADMEにまとめる
* makefileの修正をして、push
* サービスアカウント含めたアカウントの自動構築手順をドキュメントにまとめるか、スクリプトにする

**Comment by sakamomo554101** [comment]
https://cloud.google.com/blog/topics/developers-practitioners/debugging-vertex-ai-training-jobs-interactive-shell

学習パイプラインのデバッグは、上記interactive shellでデバッグできそう。

**Comment by sakamomo554101** [comment]
num_train_epocsが8でも学習が成功しているので、コミット整理と残件を整理して、PRをマージする。

* 残件
  * サービスアカウントなどの事前準備まわりの対応をちゃんとまとめる（今は雑なまとめとなっている）

**Comment by sakamomo554101** [comment]
マージして、残件を別チケットにした。
クローズ。
