### ISSUE TITLE
VertexAIのモデルモニタリングを試しに導入する

### ISSUE THREAD

**Issue by sakamomo554101** [sakamomo554101/YouyakuAI#46]
## 概要

VertexAIのモデルモニタリングを試しに導入する。
手順などをドキュメントにまとめる + スクリプトを作成する。

**Comment by sakamomo554101** [comment]
#45 の対応後に着手可能。
VertexAI Prediction APIを用いて、モニタリングができるため。

**Comment by sakamomo554101** [comment]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/model_monitoring/model_monitoring.ipynb
上記が参考になりそう。

**Comment by sakamomo554101** [comment]
タイムアウト処理必要だなぁ・・。
ダッシュボード側がレスポンスないと、ずっとグルグルしてしまう

**Comment by sakamomo554101** [comment]
ModelDeploymentMonitoringJobを使って、モニターを構築すれば良い？

**Comment by sakamomo554101** [comment]
pipeline上でモニタリングを構築するオペレーターを追加できんかなー

**Comment by sakamomo554101** [comment]
https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai
お、これ参考になりそう。

眺めてみる

**Comment by sakamomo554101** [comment]
https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/blob/main/08-model-monitoring.ipynb
上記でモニタリングを作成している

**Comment by sakamomo554101** [comment]
https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.ModelDeploymentMonitoringObjectiveConfig

ModelMonitorのコンフィグは上記っぽい。
上記にskewのパラメーターとかを入れていくように見える。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.ModelDeploymentMonitoringJob

上記でモニターを作成可能。
上記に入れるパラメーター（先程のコンフィグも含まれる。他にはアラート設定やモニタリング期間など）を解釈すれば、モニタリングが作れそう。

**Comment by sakamomo554101** [comment]
エンドポイントに紐づいたモデル情報を取る際に、EndpointServiceClientが必要。
モニタリングサービスを開始する際に、JobServiceClientが必要。

https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.services.endpoint_service.EndpointServiceClient
https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.services.job_service.JobServiceClient

**Comment by sakamomo554101** [comment]
なるほど、すでに同一エンドポイントにモニタリング設定している状態で、再度モニタリングを設定しようとすると、エラーになるっぽい。

**Comment by sakamomo554101** [comment]
モニタリングがあるかのチェックか上書き対応ができるかを調査したほうが良さそう。

**Comment by sakamomo554101** [comment]
サンプルコードが参考になる。

```python
def list_monitoring_jobs():
    client_options = dict(api_endpoint=API_ENDPOINT)
    parent = f"projects/{PROJECT_ID}/locations/us-central1"
    client = JobServiceClient(client_options=client_options)
    response = client.list_model_deployment_monitoring_jobs(parent=parent)
    print(response)


def delete_monitoring_job(job):
    client_options = dict(api_endpoint=API_ENDPOINT)
    client = JobServiceClient(client_options=client_options)
    response = client.delete_model_deployment_monitoring_job(name=job)
    print(response)
```

**Comment by sakamomo554101** [comment]
どうやって、モニタリングの存在判定をするか

**Comment by sakamomo554101** [comment]
https://googleapis.dev/python/aiplatform/latest/aiplatform_v1/job_service.html#google.cloud.aiplatform_v1.services.job_service.JobServiceClient.create_model_deployment_monitoring_job

updateもある。
https://googleapis.dev/python/aiplatform/latest/aiplatform_v1/job_service.html#google.cloud.aiplatform_v1.services.job_service.JobServiceClient.update_model_deployment_monitoring_job

**Comment by sakamomo554101** [comment]
list_model_deployment_monitoring_jobsを実行すると、
ModelDeploymentMonitoringJobのリストが返ってくるっぽい

**Comment by sakamomo554101** [comment]
多分、同一エンドポイント名が存在するかを見れば良いかなー

**Comment by sakamomo554101** [comment]
https://googleapis.dev/python/aiplatform/latest/aiplatform_v1/types.html?highlight=modeldeploymentmonitoringjob#google.cloud.aiplatform_v1.types.ModelDeploymentMonitoringJob.endpoint
上記でendpointが取れる。

**Comment by sakamomo554101** [comment]
うーん、、下記のようにFieldMaskを指定しても、エラーになってしまう。

```python
response = client.update_model_deployment_monitoring_job(
    model_deployment_monitoring_job=job, update_mask=FieldMask(paths=["*"])
)
```

**Comment by sakamomo554101** [comment]
https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/blob/f049abdf3e9837c32ee3b6faea82a2202d14581b/08-model-monitoring.ipynb

**Comment by sakamomo554101** [comment]
なるほど、ModelDeploymentMonitoringJob.nameはすでにデプロイ済みのjobから取得する必要がありそう。
※デプロイ前だと、job.nameが空文字だった。

**Comment by sakamomo554101** [comment]
https://googleapis.dev/python/aiplatform/latest/aiplatform_v1/types.html#google.cloud.aiplatform_v1.types.ModelDeploymentMonitoringJob.name
上記みても、デプロイ前後でどうか？は記載がないけどもね・・。

**Comment by sakamomo554101** [comment]
あ、そういえば、ドリフト（スキューかな）検知で利用するデータソースはcsv形式でもいいのかしら

**Comment by sakamomo554101** [comment]
https://googleapis.dev/java/google-cloud-aiplatform/1.0.0/com/google/cloud/aiplatform/v1beta1/ModelMonitoringObjectiveConfig.TrainingDataset.html

BigquerySourceではなく、GcsSource使えばいいのかも。

**Comment by sakamomo554101** [comment]
artifactのuriを取得すれば、そこに文字列が格納されてるのかも。
（endpointをカスタムコンポーネントから返す場合の取得方法）

**Comment by sakamomo554101** [comment]
いや、無理か。outputPathに指定しちゃうと、Vertex側でパスが勝手に設定されちゃうんだよな。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.ModelMonitoringObjectiveConfig.TrainingDataset

TrainingDatasetについては、上記見ればわかりそう。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.GcsSource

あー、やっぱ、urisにgcsのfile uriのリスト渡せばOKだな。

**Comment by sakamomo554101** [comment]
gcsのuriのリスト（training, validationあたり）を取得する必要があるな。

**Comment by sakamomo554101** [comment]
あれ、モデル側で、予測対象って、どう決めてたっけ？
特に決めてないのか

**Comment by sakamomo554101** [comment]
学習時に決めてるはず

**Comment by sakamomo554101** [comment]
https://github.com/sakamomo554101/YouyakuAI/blob/master/model_pipeline/components/trainer/src/dataset.py#L79-L91

csvにカラム名は書いてなくて、列数でターゲットを指定してる。
titleがターゲットなので、1列目（0指定）となる。

**Comment by sakamomo554101** [comment]
とりあえず、prediction_target_fieldには0入れてみるけど、ダメだったら、csvに列名入れるか。

**Comment by sakamomo554101** [comment]
pipelineのビルドでこける。
なんだっけ、これ。ListでpipelineParamsを受け取っているのが問題？

```
Traceback (most recent call last):
  File "model_pipeline/pipeline.py", line 844, in <module>
    pipeline_instance.compile_pipeline(
  File "model_pipeline/pipeline.py", line 280, in compile_pipeline
    v2_compiler.Compiler().compile(
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/v2/compiler/compiler.py", line 1274, in compile
    pipeline_job = self._create_pipeline_v2(
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/v2/compiler/compiler.py", line 1196, in _create_pipeline_v2
    pipeline_func(*args_list)
  File "model_pipeline/pipeline.py", line 382, in kfp_youyakuai_pipeline
    monitoring_op = self.create_monitoring_op(
  File "model_pipeline/pipeline.py", line 717, in create_monitoring_op
    return monitoring_func(
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/components/_dynamic.py", line 53, in Monitoring func
    return dict_func(locals())  # noqa: F821 TODO
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/components/_components.py", line 386, in create_task_object_from_component_and_pythonic_arguments
    return _create_task_object_from_component_and_arguments(
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/components/_components.py", line 323, in _create_task_object_from_component_and_arguments
    task = _container_task_constructor(
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/dsl/_component_bridge.py", line 319, in _create_container_op_from_component_and_arguments
    _attach_v2_specs(task, component_spec, original_arguments)
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/site-packages/kfp/dsl/_component_bridge.py", line 593, in _attach_v2_specs
    json.dumps(argument_value))
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shotasakamoto/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PipelineParam is not JSON serializable
```

**Comment by sakamomo554101** [comment]
```dataset_gcs_source_uris=dataset_gcs_source_uris``` の所をコメントアウトすると、コンパイルできるから、List指定が問題そう。

**Comment by sakamomo554101** [comment]
https://stackoverflow.com/questions/70356856/vertex-ai-model-batch-prediction-issue-with-referencing-existing-model-and-inpu

上記、同じエラーに遭遇してそう。

**Comment by sakamomo554101** [comment]
ふーむ、、コンバーターを作ると良い（= componentアノテーターなりを使って）、というイメージか。

**Comment by sakamomo554101** [comment]
んー、結局、PipelineParamがlistに入らんから、同じ問題がおきるな。

**Comment by sakamomo554101** [comment]
多分、エンドポイント にモデルがアタッチされてないから、と思ったが、下記のエラーはなんだろ？

```
Field: model_deployment_monitoring_job; Message: model_deployment_monitoring_objective_configs is empty in ModelDeploymentMonitoringJob
```

**Comment by sakamomo554101** [comment]
あー、model_idが取れなかったからか。
やはり、エンドポイント にモデルが紐づいてないのが原因。

**Comment by sakamomo554101** [comment]
んー、モデルモニタリングのデプロイタスクは成功するが、実際にモニタリングは開始されていない。
通知先のメールアドレスにデプロイが失敗した旨のメールが来てた。

**Comment by sakamomo554101** [comment]
trainingDatasetに対して、何も設定できていなかったのが問題。
GcsSourceを設定するようにしたら、モニタリングが動くようになった。
ただ、データフォーマットが見えてないのは大丈夫なのか？

```
2022-02-12T09:37:52.320125961Zmodel_deployment_monitoring_objective_configs {
情報
2022-02-12T09:37:52.320131405Z deployed_model_id: "5768856035963961344"
情報
2022-02-12T09:37:52.320136939Z objective_config {
情報
2022-02-12T09:37:52.320142387Z training_dataset {
情報
2022-02-12T09:37:52.320147521Z data_format: "data-format-unspecified"
情報
2022-02-12T09:37:52.320153215Z gcs_source {
情報
2022-02-12T09:37:52.320158741Z uris: "gs://youyaku_ai_pipeline/pipeline_output/749925056555/youyaku-ai-pipeline-20220212172750/data-generator_1178458761673572352/train_data"
情報
2022-02-12T09:37:52.320164814Z }
情報
2022-02-12T09:37:52.320170270Z target_field: "0"
情報
2022-02-12T09:37:52.320175932Z }
```

**Comment by sakamomo554101** [comment]
https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.ModelMonitoringObjectiveConfig.TrainingDataset
```
data_format
Data format of the dataset, only applicable if the input is from Google Cloud Storage. The possible formats are: "tf-record" The source file is a TFRecord file. "csv" The source file is a CSV file.
```

なるほど、csv指定するか（csvなので）

**Comment by sakamomo554101** [comment]
# 残件

* モニタリング時のcsvファイルについて、列番号指定が良いのか？を確認する（ダメな場合は、csvに対して、カラム名を設定する必要がある）
* コミット整理
* マージ

**Comment by sakamomo554101** [comment]
あ、モニタリングが途中で無効化されてる。
やはりちゃんとモニタリング出来ていない、ということか。

**Comment by sakamomo554101** [comment]
https://qiita.com/komiya_____/items/8fd900006bbb2ebeb8b8

お、to_gpqなんてあるのか。

**Comment by sakamomo554101** [comment]
とりあえず、モデルモニタリングはデプロイされた。
ちょっと放置してみて、様子みよ。

**Comment by sakamomo554101** [comment]
1時間たったが、特に特徴量のスコアとか出てこないな・・。
ちょっとモニタリングのドキュメント確認するか。

**Comment by sakamomo554101** [comment]
ダッシュボード上で、下記が表示されているのが気になる。

```
Enabled: First run of a monitoring job is pending
```

**Comment by sakamomo554101** [comment]
そもそも、input_textは原文である日本語の入力データが来るわけだから、特徴量への変換処理が必要。

それがModelMonitoring側で出来ない気がする。

**Comment by sakamomo554101** [comment]
ただ、そうすると、input_textはPredictionAPIの入力になってしまってるから、BQ側のソースを前処理しただけでは、ダメな気がする。

**Comment by sakamomo554101** [comment]
https://cloud.google.com/vertex-ai/docs/model-monitoring/using-model-monitoring?hl=ja#automatic-schema-parsing

ふむ、自動スキーマでの解析になってるから、少なくとも1000個入れないと、解析されなさそう・・。
スキーマを指定して試してみるか。

**Comment by sakamomo554101** [comment]
sample_predict_instanceは下記のような入力フォーマットで入れれば良さそうに見える。（リクエストと同じフォーマットという意味）

```json
{
  "instances": [
    {
      "input_text": "これはテストです"
    }
  ]
}
```

google.protobuf.struct_pb2.Valueという型になっているが、これはProtoBuf形式なのは分かるが、どう入れれば良い？

**Comment by sakamomo554101** [comment]
https://programtalk.com/python-examples/google.protobuf.struct_pb2.Value/
参考になりそう。

下記のように定義すれば良い？

```
message = Struct(fields={'foo': Value(bool_value=True)})
```

**Comment by sakamomo554101** [comment]
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#value
structで定義すればいいのかなー

**Comment by sakamomo554101** [comment]
うーむ、model monitoringに入ってきた入力文章だが、単純にカテゴリカルに分けられてるだけで、特徴量で統計量分布になってなさそう・・。

なんか前処理の設定とかできんのかなぁ・・。

**Comment by sakamomo554101** [comment]
structでsampleを定義する形で、ちゃんとドリフトは動くようになった。
が、前述した問題がある。

**Comment by sakamomo554101** [comment]
https://zenn.dev/hellorusk/articles/7fd588cae5b173

tokernizer.batch_encode_plusでは、bertの入力データとするように前処理をしている。
わかち書き + IDへの変換をして、arrayにしている。

**Comment by sakamomo554101** [comment]
うーん、vertex predictionの前段にpreprocessorを入れて、文字列 -> 配列にするしか無い気がする。

**Comment by sakamomo554101** [comment]
面倒なのは、tokenizerのバイナリを学習後に取得する必要がある点。

**Comment by sakamomo554101** [comment]
# 方針

* 現状のモニタリング実装はコミットとコード整理して、一旦masterにマージする。
* prediction APIをpreprocessorとモデル部分を分離する対応は別issueとする。
